default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: magic_development
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'development' } %>

test:
  <<: *default
  database: magic_test

production:
  <<: *default
  database: magic_production
  username: magic_studios
  password: <%= ENV['MAGIC_STUDIO_DATABASE_PASSWORD'] %>
